<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VacancySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('vacancy')->insert([
            [
                'id_vacancy' => 1, 
                'nib' => '1647354321', 
                'id_major' => 3, 
                'applied' => 0, 
                'title' => 'Pengembangan Aplikasi E-Commerce', 
                'salary' => '2000000', 
                'time_type' => 'full time', 
                'type' => 'online', 
                'duration' => 12,
                'quota' => 10, 
                'location' => 'Legenda Malaka', 
                'description' => 'PT Aohai membuka kesempatan bagi Anda yang berbakat dan memiliki semangat tinggi untuk bergabung sebagai Pengembang Aplikasi E-Commerce.\r\n\r\nKualifikasi:\r\n-Mahasiswa atau lulusan dari jurusan Teknik Informatika atau bidang terkait.\r\n-Memiliki pemahaman tentang pengembangan aplikasi berbasis web.\r\n-Pengalaman atau kemampuan dalam teknologi seperti HTML, CSS, JavaScript, dan \r\n   framework seperti React, Angular, atau Vue.js (nilai tambah).\r\n-Mampu bekerja dalam tim dan memiliki komunikasi yang baik.\r\n-Kreatif, inovatif, dan mampu berpikir solutif.\r\n\r\nTanggung Jawab:\r\n-Mengembangkan dan mengoptimalkan aplikasi e-commerce sesuai kebutuhan \r\n   pengguna.\r\n-Memastikan aplikasi responsif, aman, dan user-friendly.\r\n-Berkolaborasi dengan tim desain dan pengembangan untuk menghasilkan produk \r\n   yang berkualitas.\r\n-Mengidentifikasi dan memperbaiki bug atau isu yang muncul dalam aplikasi.\r\n\r\nInformasi Tambahan:\r\nGaji: Rp2.000.000/bulan\r\nDurasi: 12 bulan\r\nTipe Waktu: Full-time\r\nJenis Kerja: Online\r\nLokasi: Legenda Malaka\r\nQuota: 20 orang\r\nPeriode Pendaftaran: 14 Januari 2025 – 20 Januari 2025\r\n\r\nJadilah bagian dari tim yang berkomitmen menciptakan solusi e-commerce modern! Ayo daftarkan diri Anda dan tunjukkan potensi terbaik Anda.''2025-01-14', '2025-01-20', '2025-01-14 08:32:27', '2025-01-14 09:17:11'],
            [
                'id_vacancy' => 2, 
                'nib' => '8756431231', 
                'id_major' => 3, 
                'applied' => 0, 
                'title' => 'Sistem Rekomendasi Berbasis Machine Learning', 
                'salary' => '3000000', 
                'time_type' => 'part time', 
                'type' => 'online', 
                'duration' => '3',
                'quota' => 6, 
                'location' => 'Temenggung', 
                'description' => 'Lowongan Pekerjaan: Sistem Rekomendasi Berbasis Machine Learning\r\nJurusan: Teknik Informatika\r\nLokasi: Temenggung\r\nGaji: Rp 3.000.000 / Bulan\r\nDurasi: 3 bulan\r\nJenis Kerja: Online\r\nTipe Waktu: Paruh Waktu (Part-time)\r\nKuota: 20 orang\r\nPeriode Pendaftaran: 14 Januari 2025 - 22 Januari 2025\r\n\r\nDeskripsi Pekerjaan:\r\nKami mencari individu berbakat untuk bergabung dalam proyek pengembangan sistem rekomendasi berbasis Machine Learning. Anda akan berkontribusi dalam penelitian, pengembangan algoritma, dan implementasi teknologi canggih dalam pengolahan data dan sistem rekomendasi.\r\n\r\nKualifikasi:\r\n\r\n-Mahasiswa atau lulusan dari jurusan Teknik Informatika.\r\n-Memiliki dasar pengetahuan tentang Machine Learning dan pengembangan sistem.\r\n-Mampu bekerja secara online dan berdedikasi sesuai dengan jadwal yang ditentukan.\r\n-Mampu bekerja dalam tim dengan komunikasi yang efektif.\r\n\r\nKeuntungan:\r\n\r\n-Pengalaman berharga dalam mengembangkan proyek nyata.\r\n-Peluang memperluas jaringan profesional.\r\n-Mendapatkan gaji yang kompetitif.\r\n\r\nJika Anda berminat, segera ajukan lamaran sebelum periode pendaftaran berakhir!', 20, '2025-01-14', '2025-01-22', '2025-01-14 08:40:11', '2025-01-14 09:15:05'],
            [
                'id_vacancy' => 3, 
                'nib' => '9845563123', 
                'id_major' => 3, 
                'applied' => 0, 
                'title' => 'Optimasi Pencarian Database NoSQL', 
                'salary' => '5000000', 
                'time_type' => 'part time', 
                'type' => 'online', 
                'duration' => '3',
                'quota' => 20, 
                'location' => 'Tanjung Piayu', 
                'description' => 'Lowongan Magang: Optimasi Pencarian Database NoSQL\r\nJurusan: Teknik Informatika\r\nLokasi: Tanjung Piayu\r\nGaji: Rp 5.000.000 / Bulan\r\nDurasi: 3 bulan\r\nJenis Kerja: Online\r\nTipe Waktu: Paruh Waktu (Part-time)\r\nKuota: 20 orang\r\nPeriode Pendaftaran: 14 Januari 2025 - 23 Januari 2025\r\n\r\nDeskripsi Pekerjaan:\r\nKami membuka kesempatan magang bagi mahasiswa atau lulusan jurusan Teknik Informatika untuk bergabung dalam proyek Optimasi Pencarian Database NoSQL. Dalam proyek ini, Anda akan belajar dan berkontribusi pada analisis performa database NoSQL, merancang solusi optimasi pencarian data, dan mengimplementasikan teknik indexing serta query tuning.\r\n\r\nTanggung Jawab:\r\n\r\n-Menganalisis performa query pada database NoSQL.\r\n-Merancang strategi optimasi pencarian data.\r\n-Berkolaborasi dengan tim untuk menguji dan meningkatkan efisiensi database.\r\n-Membuat dokumentasi terkait proses dan hasil optimasi.\r\n\r\nKualifikasi:\r\n\r\n-Mahasiswa atau lulusan Teknik Informatika.\r\n-Memiliki pemahaman dasar tentang database NoSQL (seperti MongoDB, Cassandra, \r\n   atau Redis).\r\n-Menguasai konsep indexing dan pengelolaan database.\r\n-Mampu bekerja secara online dan berkolaborasi dalam tim.\r\n-Memiliki motivasi tinggi untuk belajar dan menyelesaikan tantangan teknis.\r\n\r\nKeuntungan:\r\n\r\n-Mendapatkan pengalaman langsung dalam optimasi sistem database.\r\n-Gaji kompetitif selama program magang.\r\n-Kesempatan untuk bekerja pada proyek nyata yang menantang.\r\n-Pengembangan keterampilan profesional di bidang teknologi database.\r\n\r\nJika Anda tertarik untuk bergabung dalam proyek ini, segera ajukan lamaran sebelum pendaftaran ditutup!', 20, '2025-01-14', '2025-01-23', '2025-01-14 08:44:51', '2025-01-14 08:44:51'],
            [
                'id_vacancy' => 4, 
                'nib' => '9845563123', 
                'id_major' => 3, 
                'applied' => 0, 
                'title' => 'Aplikasi Manajemen Proyek Kolaboratif', 
                'salary' => '2500000', 
                'time_type' => 'part time', 
                'type' => 'online', 
                'duration' => '3', 
                'quota' => 15,
                'location' => 'Tanjung Piayu', 
                'description' => 'Lowongan Magang: Aplikasi Manajemen Proyek Kolaboratif\r\nJurusan: Teknik Informatika\r\nLokasi: Tanjung Piayu\r\nGaji: Rp 2.500.000 / Bulan\r\nDurasi: 3 bulan\r\nJenis Kerja: Online\r\nTipe Waktu: Paruh Waktu (Part-time)\r\nKuota: 10 orang\r\nPeriode Pendaftaran: 14 Januari 2025 - 22 Januari 2025\r\n\r\nDeskripsi Pekerjaan:\r\nKami mengundang individu berbakat untuk mengikuti program magang pada proyek Aplikasi Manajemen Proyek Kolaboratif. Dalam proyek ini, Anda akan terlibat dalam pengembangan aplikasi berbasis web yang mendukung kolaborasi tim, pengelolaan tugas, dan pelaporan proyek secara real-time.\r\n\r\nTanggung Jawab:\r\n\r\n-Merancang dan mengembangkan fitur aplikasi untuk mendukung manajemen proyek.\r\n-Mengimplementasikan sistem kolaborasi berbasis pengguna secara online.\r\n-Mengoptimalkan antarmuka pengguna untuk pengalaman terbaik.\r\n-Menguji dan memperbaiki aplikasi untuk memastikan performa optimal.\r\n\r\nKualifikasi:\r\n\r\n-Mahasiswa atau lulusan Teknik Informatika.\r\n-Memiliki pemahaman dasar tentang pengembangan aplikasi web (frontend dan \r\n   backend).\r\n-Berpengalaman dengan framework modern seperti React, Angular, atau Laravel (nilai \r\n   tambah).\r\n-Mampu bekerja secara online dengan komunikasi yang baik.\r\n-Mampu beradaptasi dengan tugas dan tantangan baru.\r\n\r\nKeuntungan:\r\n\r\n-Pengalaman langsung dalam pengembangan aplikasi berbasis proyek nyata.\r\n-Mendapatkan gaji selama program magang berlangsung.\r\n-Kesempatan untuk memperluas pengetahuan di bidang pengembangan perangkat \r\n   lunak kolaboratif.\r\n-Menambah portofolio dengan hasil kerja yang nyata.\r\n\r\nJangan lewatkan kesempatan untuk bergabung dengan tim kami! Segera ajukan lamaran sebelum batas waktu pendaftaran berakhir.', 10, '2025-01-14', '2025-01-22', '2025-01-14 08:47:57', '2025-01-14 08:47:57'],
            [
                'id_vacancy' => 5, 
                'nib' => '1983214321', 
                'id_major' => 3, 
                'applied' => 0, 
                'title' => 'Keamanan Jaringan dengan Enkripsi', 
                'salary' => '3000000', 
                'time_type' => 'part time', 
                'type' => 'hybrid', 
                'duration' => '5', 
                'quota' => 5,
                'location' => 'Bengkong', 
                'description' => 'Deskripsi Pekerjaan:\r\nKami mencari peserta magang yang bersemangat untuk bergabung dalam proyek Keamanan Jaringan dengan Enkripsi. Proyek ini akan fokus pada penerapan teknologi enkripsi untuk melindungi data yang ditransmisikan melalui jaringan, sekaligus memastikan keamanan dan integritas informasi.\r\n\r\nTanggung Jawab:\r\n\r\n-Menganalisis risiko keamanan pada jaringan dan data yang ditransmisikan.\r\n-Mengembangkan dan mengimplementasikan algoritma enkripsi untuk perlindungan \r\n   data.\r\n-Mengintegrasikan teknologi enkripsi ke dalam sistem jaringan.\r\n-Menguji dan memastikan keamanan data dalam berbagai skenario serangan.\r\n\r\nKualifikasi:\r\n\r\n-Mahasiswa atau lulusan Teknik Informatika.\r\n-Memiliki pemahaman dasar tentang keamanan jaringan dan algoritma enkripsi (AES, \r\n   RSA, dsb.).\r\n-Berpengalaman menggunakan tools keamanan jaringan (Wireshark, OpenSSL, atau \r\n   sejenisnya) menjadi nilai tambah.\r\n-Mampu bekerja secara online dan berdedikasi dalam tim.\r\n-Memiliki keinginan untuk belajar lebih dalam tentang teknologi keamanan.\r\n\r\nKeuntungan:\r\n\r\n-Pengalaman nyata dalam pengembangan sistem keamanan jaringan.\r\n-Gaji kompetitif selama program magang berlangsung.\r\n-Peluang memperluas pengetahuan dan keterampilan di bidang keamanan siber.\r\n-Menambah nilai portofolio melalui proyek yang relevan dengan industri.\r\n\r\nJika Anda tertarik untuk mengasah keterampilan dan berkontribusi pada pengembangan teknologi keamanan, segera ajukan lamaran sebelum pendaftaran ditutup!', 15, '2025-01-14', '2025-01-23', '2025-01-14 08:51:03', '2025-01-14 08:51:03'],
            [
                'id_vacancy' => 6, 
                'nib' => '1983214321', 
                'id_major' => 3, 
                'applied' => 0, 
                'title' => 'Analisis Sentimen Media Sosial', 
                'salary' => '1500000', 
                'time_type' => 'part time', 
                'type' => 'hybrid', 
                'duration' => '1', 
                'quota' => 13,
                'location' => 'Bengkong', 
                'description' => 'Deskripsi Pekerjaan:\r\nKami membuka kesempatan magang untuk mahasiswa atau lulusan jurusan Teknik Informatika yang ingin mengembangkan keterampilan di bidang Analisis Sentimen Media Sosial. Proyek ini akan fokus pada pengumpulan, analisis, dan interpretasi data dari berbagai platform media sosial untuk memahami pola sentimen publik.\r\n\r\nTanggung Jawab:\r\n\r\n-Mengumpulkan data dari berbagai platform media sosial menggunakan API atau \r\n  tools web scraping.\r\n-Menganalisis data untuk mengidentifikasi pola sentimen (positif, negatif, netral).\r\n-Menggunakan teknik Natural Language Processing (NLP) untuk analisis teks.\r\n-Membuat visualisasi data dan laporan analisis untuk mendukung pengambilan \r\n   keputusan.\r\n\r\nKualifikasi:\r\n\r\n-Mahasiswa atau lulusan Teknik Informatika.\r\n-Memiliki pengetahuan dasar tentang pengolahan data dan analisis teks.\r\n-Familiar dengan tools dan bahasa pemrograman seperti Python, R, atau SQL.\r\n-Berpengalaman menggunakan pustaka NLP seperti NLTK, spaCy, atau Transformers \r\n   (nilai tambah).\r\n-Mampu bekerja secara online dan memiliki komunikasi yang baik.\r\n\r\nKeuntungan:\r\n\r\n-Pengalaman langsung dalam menganalisis data media sosial.\r\n-Gaji kompetitif selama program magang.\r\n-Kesempatan untuk mempelajari teknik dan alat terbaru di bidang analitik data.\r\n-Menambah portofolio profesional dengan proyek nyata yang relevan dengan tren \r\n   industri.\r\n\r\nJangan lewatkan kesempatan untuk bergabung dalam proyek menarik ini! Segera ajukan lamaran sebelum periode pendaftaran berakhir.', 10, '2025-01-14', '2025-01-31', '2025-01-14 08:53:13', '2025-01-14 08:53:13'],
            [
                'id_vacancy' => 7, 
                'nib' => '7765902312', 
                'id_major' => 3, 
                'applied' => 0, 
                'title' => 'Aplikasi Chatbot untuk Layanan Pelanggan', 
                'salary' => '5000000', 
                'time_type' => 'full time', 
                'type' => 'online', 
                'duration' => '3',
                'quota' => 6, 
                'location' => 'Tiban', 
                'description' => 'Deskripsi Pekerjaan:\r\nKami membuka kesempatan magang untuk mahasiswa atau lulusan Teknik Informatika yang ingin terlibat dalam pengembangan Aplikasi Chatbot untuk Layanan Pelanggan. Proyek ini bertujuan untuk mengembangkan chatbot berbasis kecerdasan buatan yang dapat membantu meningkatkan pengalaman pelanggan dengan memberikan respons cepat dan akurat.\r\n\r\nTanggung Jawab:\r\n\r\n-Merancang dan mengembangkan chatbot untuk layanan pelanggan.\r\n-Mengintegrasikan chatbot dengan platform komunikasi seperti WhatsApp, Telegram, \r\n   atau situs web.\r\n-Melatih chatbot menggunakan teknik Natural Language Processing (NLP) agar dapat \r\n   memahami dan merespons pertanyaan pelanggan secara otomatis.\r\n-Menguji dan meningkatkan performa chatbot berdasarkan masukan pengguna.\r\n\r\nKualifikasi:\r\n\r\n-Mahasiswa atau lulusan Teknik Informatika.\r\n-Memiliki pemahaman tentang pengembangan chatbot dan kecerdasan buatan.\r\n-Berpengalaman menggunakan framework chatbot seperti Dialogflow, Rasa, atau \r\n   Microsoft Bot Framework (nilai tambah).\r\n-Menguasai bahasa pemrograman seperti Python atau JavaScript.\r\n-Mampu bekerja secara online dan berkolaborasi dalam tim.\r\n\r\nKeuntungan:\r\n\r\n-Pengalaman langsung dalam pengembangan aplikasi berbasis AI.\r\n-Gaji kompetitif selama program magang berlangsung.\r\n-Kesempatan belajar dan menggunakan teknologi terkini di bidang AI dan NLP.\r\n-Menambah nilai portofolio dengan proyek berbasis teknologi inovatif.\r\n\r\nJika Anda memiliki semangat untuk belajar dan berkontribusi dalam menciptakan solusi layanan pelanggan berbasis teknologi, segera daftarkan diri Anda sebelum pendaftaran ditutup!', 12, '2025-01-14', '2025-01-14', '2025-01-14 08:55:58', '2025-01-14 08:55:58'],
            [
                'id_vacancy' => 8, 
                'nib' => '6648921221', 
                'id_major' => 3, 
                'applied' => 0, 
                'title' => 'Sistem Informasi Akademik Berbasis Web', 
                'salary' => '6000000', 
                'time_type' => 'part time', 
                'type' => 'online', 
                'duration' => '4',
                'quota' => 8, 
                'location' => 'Nongsa', 
                'description' => 'Deskripsi Pekerjaan:\r\nKami membuka kesempatan magang untuk mahasiswa atau lulusan Teknik Informatika yang ingin berkontribusi dalam pengembangan Sistem Informasi Akademik Berbasis Web. Proyek ini bertujuan untuk menciptakan aplikasi web yang mempermudah pengelolaan data akademik, termasuk jadwal, nilai, dan administrasi mahasiswa.\r\n\r\nTanggung Jawab:\r\n\r\n-Merancang dan mengembangkan fitur-fitur sistem informasi akademik berbasis web.\r\n-Mengintegrasikan sistem dengan database untuk pengelolaan data akademik.\r\n-Mengoptimalkan antarmuka pengguna agar mudah digunakan oleh berbagai pihak \r\n   (admin, dosen, mahasiswa).\r\n-Menguji dan memastikan sistem berjalan dengan baik tanpa kendala teknis.\r\n\r\nKualifikasi:\r\n\r\n-Mahasiswa atau lulusan Teknik Informatika.\r\n-Memiliki pemahaman tentang pengembangan aplikasi web (frontend dan backend).\r\n-Menguasai bahasa pemrograman seperti PHP, JavaScript, atau Python.\r\n-Familiar dengan framework seperti Laravel, Django, atau React (nilai tambah).\r\n-Memiliki pengalaman dengan pengelolaan database seperti MySQL atau \r\n   PostgreSQL.\r\n-Mampu bekerja secara online dan berkomunikasi dengan baik dalam tim.\r\n\r\nKeuntungan:\r\n\r\n-Pengalaman langsung dalam mengembangkan sistem informasi skala besar.\r\n-Gaji kompetitif selama program magang berlangsung.\r\n-Kesempatan untuk memperluas keterampilan teknis dan manajemen proyek.\r\n-Menambah nilai portofolio dengan proyek nyata yang relevan dengan kebutuhan \r\n   industri.\r\n\r\nJika Anda tertarik untuk menjadi bagian dari proyek ini, segera kirimkan lamaran Anda sebelum batas waktu pendaftaran berakhir!', 20, '2025-01-14', '2025-01-31', '2025-01-14 08:59:15', '2025-01-14 08:59:15'],
            [
                'id_vacancy' => 9, 
                'nib' => '6648921221', 
                'id_major' => 3, 
                'applied' => 0, 
                'title' => 'Pengolahan Citra Menggunakan Deep Learning', 
                'salary' => '3000000', 
                'time_type' => 'part time', 
                'type' => 'online', 
                'duration' => '4',
                'quota' => 10, 
                'location' => 'Nongsa', 
                'description' => 'Deskripsi Pekerjaan:\r\nKami mengundang mahasiswa atau lulusan Teknik Informatika untuk bergabung dalam program magang dengan fokus pada Pengolahan Citra Menggunakan Deep Learning. Proyek ini bertujuan untuk mengembangkan dan menerapkan model deep learning untuk analisis dan pengolahan citra dalam berbagai aplikasi, seperti deteksi objek, segmentasi gambar, dan pengenalan pola.\r\n\r\nTanggung Jawab:\r\n\r\n-Mengembangkan model deep learning untuk pengolahan citra.\r\n-Melakukan pra-pemrosesan data citra untuk pelatihan model.\r\n-Menggunakan pustaka deep learning seperti TensorFlow, PyTorch, atau Keras.\r\n-Melakukan evaluasi performa model dan meningkatkan akurasinya.\r\n-Menyusun dokumentasi teknis terkait pengembangan dan hasil proyek.\r\n\r\nKualifikasi:\r\n\r\n-Mahasiswa atau lulusan Teknik Informatika.\r\n-Memiliki dasar pemahaman tentang pengolahan citra dan deep learning.\r\n-Familiar dengan framework seperti TensorFlow atau PyTorch.\r\n-Menguasai bahasa pemrograman Python dan pustaka seperti OpenCV atau NumPy.\r\n-Memiliki kemampuan analisis data dan pengujian model.\r\n-Mampu bekerja secara online dan berkomunikasi secara efektif dalam tim.\r\n\r\nKeuntungan:\r\n\r\n-Pengalaman langsung dalam implementasi teknologi deep learning untuk \r\n   pengolahan citra.\r\n-Gaji kompetitif selama program magang berlangsung.\r\n-Kesempatan belajar dan menguasai teknologi terkini di bidang AI dan computer \r\n   vision.\r\n-Menambah portofolio profesional dengan proyek nyata yang relevan dengan tren \r\n   teknologi.\r\n\r\nJika Anda tertarik untuk mempelajari lebih dalam tentang deep learning dan pengolahan citra, segera ajukan lamaran sebelum pendaftaran ditutup!', 13, '2025-01-14', '2025-01-29', '2025-01-14 09:02:02', '2025-01-14 09:02:02'],
            [
                'id_vacancy' => 10, 
                'nib' => '8864099912', 
                'id_major' => 3, 
                'applied' => 0, 
                'title' => 'Cloud Computing untuk Pengelolaan Data', 
                'salary' => '4000000', 
                'time_type' => 'full time', 
                'type' => 'hybrid', 
                'duration' => '5',
                'quota' => 4, 
                'location' => 'Nongsa', 
                'description' => 'Deskripsi Pekerjaan:\r\nKami membuka kesempatan magang untuk mahasiswa atau lulusan Teknik Informatika yang tertarik untuk mendalami Cloud Computing untuk Pengelolaan Data. Proyek ini bertujuan untuk mengelola dan mengoptimalkan data menggunakan platform cloud modern, memastikan keamanan, skalabilitas, dan efisiensi sistem.\r\n\r\nTanggung Jawab:\r\n\r\n-Merancang dan mengimplementasikan solusi pengelolaan data berbasis cloud.\r\n-Menggunakan layanan cloud seperti AWS, Google Cloud, atau Microsoft Azure.\r\n-Mengelola database terdistribusi di cloud untuk penyimpanan dan analisis data.\r\n-Memastikan keamanan data dan manajemen akses di lingkungan cloud.\r\n-Melakukan pengujian performa dan optimasi sistem berbasis cloud.\r\n\r\nKualifikasi:\r\n\r\n-Mahasiswa atau lulusan Teknik Informatika.\r\n-Memiliki pengetahuan dasar tentang konsep cloud computing dan pengelolaan data.\r\n-Familiar dengan layanan cloud seperti AWS S3, Google Cloud Storage, atau Azure \r\n   Blob Storage.\r\n-Menguasai bahasa pemrograman seperti Python, Java, atau Go untuk integrasi cloud.\r\n-Mampu memahami konsep keamanan data dan manajemen pengguna di cloud.\r\n-Mampu bekerja secara online dengan kolaborasi yang baik dalam tim.\r\n\r\nKeuntungan:\r\n\r\n-Pengalaman langsung dalam penerapan teknologi cloud computing.\r\n-Gaji kompetitif selama program magang berlangsung.\r\n-Kesempatan belajar teknologi terbaru di bidang cloud dan data management.\r\n-Menambah portofolio profesional dengan proyek berbasis cloud computing yang \r\n   relevan.\r\n\r\nJika Anda memiliki semangat untuk belajar dan berkontribusi dalam pengelolaan data berbasis cloud, segera kirimkan lamaran Anda sebelum pendaftaran ditutup!', 15, '2025-01-14', '2025-01-29', '2025-01-14 09:04:56', '2025-01-14 09:04:56'],
            [
                'id_vacancy' => 11, 
                'nib' => '8864099912', 
                'id_major' => 3, 
                'applied' => 0, 
                'title' => 'Aplikasi Pengelolaan Keuangan Pribadi', 
                'salary' => '4000000', 
                'time_type' => 'part time', 
                'type' => 'online', 
                'duration' => '7',
                'quota' => 12, 
                'location' => 'Nongsa', 
                'description' => 'Deskripsi Pekerjaan:\r\nKami membuka peluang magang untuk mahasiswa atau lulusan Teknik Informatika yang ingin berkontribusi dalam pengembangan Aplikasi Pengelolaan Keuangan Pribadi. Proyek ini bertujuan untuk menciptakan solusi digital yang membantu pengguna dalam mengatur anggaran, melacak pengeluaran, dan mencapai tujuan keuangan.\r\n\r\nTanggung Jawab:\r\n\r\n-Merancang dan mengembangkan aplikasi pengelolaan keuangan pribadi berbasis \r\n   web atau mobile.\r\n-Mengintegrasikan fitur seperti pelacakan pengeluaran, pencatatan pendapatan, dan \r\n   pengingat tagihan.\r\n-Mengoptimalkan antarmuka pengguna agar mudah digunakan dan intuitif.\r\n-Menyediakan fitur analitik sederhana untuk membantu pengguna memahami pola \r\n   keuangan mereka.\r\n-Menguji dan memperbaiki aplikasi berdasarkan masukan pengguna.\r\n\r\nKualifikasi:\r\n\r\n-Mahasiswa atau lulusan Teknik Informatika.\r\n-Memiliki pemahaman dasar tentang pengembangan aplikasi mobile atau web.\r\n-Menguasai bahasa pemrograman seperti JavaScript, Python, atau Kotlin (untuk - \r\n   Android).\r\n-Familiar dengan framework seperti React Native, Flutter, atau Laravel (nilai tambah).\r\n-Memiliki pengetahuan dasar tentang konsep keuangan pribadi dan pengelolaan data.\r\n-Mampu bekerja secara online dan memiliki keterampilan komunikasi yang baik.\r\n\r\nKeuntungan:\r\n\r\n-Pengalaman langsung dalam pengembangan aplikasi yang relevan dengan \r\n   kebutuhan masyarakat.\r\n-Gaji kompetitif selama program magang berlangsung.\r\n-Kesempatan belajar teknologi terkini dalam pengembangan aplikasi keuangan.\r\n-Menambah portofolio profesional dengan aplikasi yang siap digunakan oleh \r\n   pengguna.\r\n\r\nJika Anda tertarik untuk berkontribusi dalam pengembangan solusi keuangan yang inovatif, segera ajukan lamaran sebelum pendaftaran ditutup!', 15, '2025-01-14', '2025-01-28', '2025-01-14 09:06:55', '2025-01-14 09:06:55'],
            [
                'id_vacancy' => 12, 
                'nib' => '1983647321', 
                'id_major' => 3, 
                'applied' => 0, 
                'title' => 'Sistem Pembayaran Digital untuk E-Commerce', 
                'salary' => '6000000', 
                'time_type' => 'full time', 
                'type' => 'hybrid', 
                'duration' => '5',
                'quota' => 4, 
                'location' => 'Tiban', 
                'description' => 'Deskripsi Pekerjaan:\r\nKami sedang mencari tenaga ahli untuk mengembangkan sistem pembayaran digital yang dapat diimplementasikan pada platform e-commerce. Anda akan berkolaborasi dengan tim untuk merancang, membangun, dan menguji solusi inovatif di bidang teknologi finansial.\r\n\r\nTugas dan Tanggung Jawab:\r\n\r\n-Mengembangkan sistem pembayaran digital berbasis teknologi modern.\r\n-Mengintegrasikan sistem pembayaran dengan platform e-commerce.\r\n-Menjamin keamanan dan skalabilitas sistem.\r\n-Melakukan troubleshooting dan perbaikan jika terjadi masalah teknis.\r\n-Berkoordinasi dengan tim untuk memastikan proyek selesai tepat waktu.\r\n\r\nKualifikasi:\r\n\r\n-Lulusan atau mahasiswa Teknik Informatika.\r\n-Pengalaman dalam pengembangan sistem atau aplikasi adalah nilai tambah.\r\n-Mampu bekerja dalam tim dan memiliki kemampuan komunikasi yang baik.\r\n-Pengetahuan dalam teknologi pembayaran digital akan menjadi keunggulan.\r\n\r\nBergabunglah dengan kami untuk menciptakan solusi teknologi yang inovatif di dunia e-commerce.', 15, '2025-01-14', '2025-01-22', '2025-01-14 09:11:25', '2025-01-14 09:11:25'],
            [
                'id_vacancy' => 13, 
                'nib' => '2309817463', 
                'id_major' => 3, 
                'applied' => 0, 
                'title' => 'DevOps untuk Pengembangan Aplikasi Web', 
                'salary' => '6000000', 
                'time_type' => 'full time', 
                'type' => 'online', 
                'duration' => '7',
                'quota' => 10,
                'location' => 'Muka Kuning', 
                'description' => 'Deskripsi Pekerjaan:\r\nKami membuka lowongan untuk posisi DevOps yang bertanggung jawab atas pengelolaan dan pengembangan aplikasi web berbasis teknologi cloud. Posisi ini memungkinkan Anda untuk bekerja sepenuhnya secara online dengan fleksibilitas waktu kerja.\r\n\r\nTugas dan Tanggung Jawab:\r\n\r\n1.Mengelola proses CI/CD untuk aplikasi web.\r\n2.Memastikan infrastruktur cloud berjalan stabil dan efisien.\r\n3.Melakukan monitoring terhadap performa aplikasi dan sistem.\r\n4.Berkoordinasi dengan tim developer untuk integrasi fitur baru.\r\n5.Menjamin keamanan dan kelangsungan infrastruktur aplikasi.\r\n\r\nKualifikasi:\r\n\r\n-Lulusan atau mahasiswa Teknik Informatika.\r\n-Pengalaman dengan alat DevOps seperti Jenkins, Docker, atau Kubernetes.\r\n   Pengetahuan tentang pengelolaan server dan cloud computing (AWS, GCP, atau \r\n   Azure).\r\n-Kemampuan problem-solving yang baik dan dapat bekerja secara mandiri.\r\n\r\nBergabunglah dengan tim kami untuk menciptakan sistem yang andal dan inovatif di dunia pengembangan aplikasi web.', 15, '2025-01-14', '2025-01-20', '2025-01-14 09:14:08', '2025-01-14 09:14:08']
        ]);
    }
}
